connection:
    map:
        article_category: article.category
        article_post: article.post
        article_tag: article.tag
        article_tag_post: article.tag_post
        eq_migration: migration
#        defaultConnection: mysqlServer
#        defaultConnection: sqliteServer
#    defaultConnection: pgsqlServer
#    connections:
#        mysqlServer:
#            driver: mysql
#            host: localhost
#            database: symfony-on-rails
#            username: root
#        pgsqlServer:
#            driver: pgsql
#            host: localhost
#            database: symfony-on-rails
#            username: postgres
#            password: postgres
#        sqliteServer:
#            driver: sqlite
#            database: /var/sqlite/default.sqlite
fixture:
    directory:
        - /src/Fixtures
migrate:
    directory:
        - /src/Migrations
